# Generated by Django 3.1 on 2021-04-23 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_categorias_descripcion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productos',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
    ]
