# Generated by Django 3.1.6 on 2021-02-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_auto_20210206_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='nombre',
            field=models.CharField(max_length=90, unique=True, verbose_name='Nombre'),
        ),
    ]
